on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - run: cargo fmt --all -- --check

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.56.0" # Minimum supported version (from gtk-rs)
        os:
          - ubuntu-22.04
          - macos-latest
    steps:
      - run: sudo apt-get update -y
        if: matrix.os == 'ubuntu-22.04'
      - run: sudo apt-get install -y libgtk-4-dev curl libcairo-gobject2 libcairo2-dev
        if: matrix.os == 'ubuntu-22.04'
      - run: brew update
        if: matrix.os == 'macos-latest'
      - run: brew install gtk4 cairo atk
        if: matrix.os == 'macos-latest'
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          os: $${{ matrix.os }}
          components: clippy
          override: true
      - name: compile
        run: cargo build
      - name: clippy
        run: cargo clippy
